name: build docker image
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - compose.yml
      - .env
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: build docker image
    runs-on: self-hosted

    steps:
      - name: Convert repository to lowercase
        id: lowercase
        run: |
          lowercase_repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repository=$lowercase_repo" >> $GITHUB_OUTPUT

      - name: Copy repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: linuxfight
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.lowercase.outputs.repository }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.lowercase.outputs.repository }}:buildcache
          cache-to: type=registry,ref=${{ steps.lowercase.outputs.repository }}:buildcache,mode=max
